# Generated by Django 4.2.11 on 2024-03-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(related_name='members', to='main_app.team'),
        ),
    ]
