# Generated by Django 4.2.11 on 2024-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(null=True, related_name='members', to='main_app.team'),
        ),
    ]
