# Generated by Django 4.2.11 on 2024-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_user_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(related_name='members', to='main_app.team'),
        ),
    ]
