# Generated by Django 4.2.11 on 2024-03-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_user_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='progress',
            new_name='status',
        ),
    ]
